[package]
name = "bctop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = { version="0.19", features=["crossterm"] }
crossterm = "0.25"
docker-api = { git="https://github.com/vv9k/docker-api-rs", branch="master", features= ["swarm"] }
futures = "0.3"
tokio = {version="1.21", features=["rt-multi-thread", "macros"]}
eyre = "0.6"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
chrono = "0.4"
